"use strict";
Object.defineProperty(exports, "__esModule", {
  value: !0,
}),
  (exports.ModLanguage = void 0);
const puerts_1 = require("puerts"),
  UE = require("ue"),
  Info_1 = require("../../../Core/Common/Info"),
  Log_1 = require("../../../Core/Common/Log"),
  ModManager_1 = require("../ModManager"),
  LanguageSystem_1 = require("../../../Core/Common/LanguageSystem");

class ModLanguage {
  static GetCurrLang() {
    switch (ModManager_1.ModManager.Settings.Language) {
      case "English":
        return "En";
      case "简体中文":
        return "Zh";
      case "日本語":
        return "Ja";
      case "Español":
        return "Es";
      case "Indonesia":
        return "Id";
      case "Vietnamese":
        return "Vi";
      case "Korean":
        return "Ko";
      default:
        return "En";
    }
  }

  static Langs = [
    "English",
    "简体中文",
    "日本語",
    "Español",
    "Indonesia",
    "Vietnamese",
    "Korean",
  ];

  static translate = [
    {
      Text: "CUSTOM_TP_INS",
      Zh: "自定义传送 [Ins]",
      En: "Custom Teleport [Ins]",
      Es: "Teleportación Personalizada [Ins]",
      Id: "Kustomisasi Teleport [Ins]",
      Ja: "てきとうな瞬間移動 [Ins]",
      Ko: "사용자 정의 텔레포트 [Ins]",
      Vi: "Dịch Chuyển Tùy Chỉnh [Ins]",
    },
    {
      Text: "COLOR_ON",
      Zh: " : <color=green>开启</color> |",
      En: " : <color=green>ON</color> |",
      Es: " : <color=green>ACTIVO</color> |",
      Id: " : <color=green>ON</color> |",
      Ja: " : <color=green>オン</color>",
      Ko: " : <color=greko>에</color> |",
      Vi: " : <color=green>BẬT</color> |",
    },
    {
      Text: "COLOR_OFF",
      Zh: " : <color=red>关闭</color> |",
      En: " : <color=red>OFF</color> |",
      Es: " : <color=red>DESACTIVADO</color> |",
      Id: " : <color=red>OFF</color> |",
      Ja: " : <color=red>オフ</color>",
      Ko: " : <color=red>끄다</color> |",
      Vi: " : <color=red>TẮT</color> |",
    },
    {
      Text: "TEXT_ON",
      Zh: "开启",
      En: "ON",
      Es: "ACTIVO",
      Id: "ON",
      Ja: "オン",
      Ko: "에",
      Vi: "Bật",
    },
    {
      Text: "TEXT_OFF",
      Zh: "关闭",
      En: "OFF",
      Es: "DESACTIVADO",
      Id: "OFF",
      Ja: "オフ",
      Ko: "끄다",
      Vi: "TẮT",
    },
    {
      Text: "TEXT_GOD_MODE",
      Zh: "无敌模式 [F5]",
      En: "God Mode [F5]",
      Es: "Modo Dios [F5]",
      Id: "Mode Dewa [F5]",
      Ja: "神モードやで [F5]",
      Ko: "신 모드 [F5]",
      Vi: "Bất Tử [F5]",
    },
    {
      Text: "TEXT_HIT_MULTIPLIER",
      Zh: "多倍攻击 [F6]",
      En: "Hit Multiplier [F6]",
      Es: "Golpe Multiplicador [F6]",
      Id: "Pengganda Hit [F6]",
      Ja: "ヒット倍率 [F6]",
      Ko: "히트 멀티플라이어 [F6]",
      Vi: "Số Lượng Đòn Đánh [F6]",
    },
    {
      Text: "TEXT_AUTO_PICK_TREASURE",
      Zh: "拾取宝箱 [F7]",
      En: "Auto Pick Treasure [F7]",
      Es: "Auto Recoger Tesoro [F7]",
      Id: "Ambil Harta Otomatis [F7]",
      Ja: "自動で宝を拾うんや [F7]",
      Ko: "자동 보물 선택 [F7]",
      Vi: "Tự Động Nhặt Phần Thưởng [F7]",
    },
    {
      Text: "TEXT_AUTO_ABSORB",
      Zh: "自动吸收 [F8]",
      En: "Auto Absorb [F8]",
      Es: "Absorción Automática de Eco [F8]",
      Id: "Absorpsi Echo Otomatis [F8]",
      Ja: "自動エコー吸収 [F8]",
      Ko: "자동 에코 흡수 [F8]",
      Vi: "Tự Động Hấp Thụ Echo [F8]",
    },
    {
      Text: "TEXT_HIT_ALL",
      Zh: "全部命中 [F9]",
      En: "Hit All [F9]",
      Es: "Golpear todo [F9]",
      Id: "Pukul Semua [F9]",
      Ja: "すべてヒット [F9]",
      Ko: "모두 히트 [F9]",
      Vi: "Nhấn tất cả [F9]",
    },
    {
      Text: "TEXT_PERCEPTION_RANGE",
      Zh: "感知范围 [F10]",
      En: "Interaction Range [F10]",
      Es: "Rango de Interacción [F10]",
      Id: "Jarak Interaksi [F10]",
      Ja: "相互作用範囲 [F10]",
      Ko: "상호작용 범위 [F10]",
      Vi: "Phạm vi tương tác [F10]",
    },
    {
      Text: "TEXT_NO_COOLDOWN",
      Zh: "无冷却 [F11]",
      En: "No Cooldown [F11]",
      Es: "Sin Enfriamiento [F11]",
      Id: "Tanpa Cooldown [F11]",
      Ja: "クールダウンなしやで [F11]",
      Ko: "쿨다운 없음 [F11]",
      Vi: "Không Thời Gian Hồi Chiêu [F11]",
    },
    {
      Text: "TEXT_PLAYER_SPEED",
      Zh: "玩家速度 [F12]",
      En: "Player Speed [F12]",
      Es: "Velocidad del Jugador [F12]",
      Id: "Kecepatan Pemain [F12]",
      Ja: "プレイヤーのスピードやで [F12]",
      Ko: "플레이어 속도 [F12]",
      Vi: "Tốc độ nhân vật [F12]",
    },
    {
      Text: "TEXT_CUSTOM_TP",
      Zh: "自定义传送 [INS]",
      En: "Custom Teleport [INS]",
      Es: "Teleportación Personalizada [INS]",
      Id: "Teleportasi Kustom [INS]",
      Ja: "てきとうな瞬間移動 [INS]",
      Ko: "사용자 정의 텔레포트 [INS]",
      Vi: "Dịch Chuyển Tùy Chỉnh [INS]",
    },
    {
      Text: "TEXT_AUTO_LOOT",
      Zh: "自动拾取 [Num0]",
      En: "Auto Loot [Num0]",
      Es: "Colección de juegos automáticos [Num0]",
      Id: "Pengambil Koleksi Otomatis [Num0]",
      Ja: "自動小冊子の保存 [Num0]",
      Ko: "자동 콜렉시 펜감빌 [Num0]",
      Vi: "bộ sưu tập tự động hóa [Num0]",
    },
    {
      Text: "TEXT_CUSTOM_TP_STATE",
      Zh: "自定义传送状态 [Insert]:",
      En: "Custom Teleport State [Insert]:",
      Es: "Estado de Teleportación Personalizada [Insert]:",
      Id: "Status Teleportasi Kustom [Insert]:",
      Ja: "カスタムテレポートの状態 [Insert]",
      Ko: "사용자 정의 텔레포트 상태 [Insert]:",
      Vi: "Trạng thái dịch chuyển [Insert]:",
    },
    {
      Text: "TEXT_SHOW_DEL",
      Zh: " 显示 [Del]",
      En: " Show [Del]",
      Es: " Mostrar [Del]",
      Id: " Tampilkan [Del]",
      Ja: " ショー [Del]",
      Ko: " 보여주다 [Del]",
      Vi: " Hiện [Del]",
    },
    {
      Text: "TEXT_CURR_FILE",
      Zh: "当前文件:",
      En: "Current File:",
      Es: "Archivo Actual:",
      Id: "File Saat Ini:",
      Ja: "今のファイル:",
      Ko: "현재 파일:",
      Vi: "File Hiện Tại:",
    },
    {
      Text: "TEXT_PREV_FILE",
      Zh: "| 上一个文件 [PageUp]:",
      En: "| Previous File [PageUp]:",
      Es: "| Archivo Anterior [PageUp]:",
      Id: "| File Sebelumnya [PageUp]:",
      Ja: "| 前のファイル [PageUp]",
      Ko: "| 이전 파일 [PageUp]:",
      Vi: "| File Trước [PageUp]:",
    },
    {
      Text: "TEXT_NEXT_FILE",
      Zh: " | 下一个文件 [PageDown]:",
      En: " | Next File [PageDown]:",
      Es: " | Archivo Siguiente [PageDown]:",
      Id: " | File Berikutnya [PageDown]:",
      Ja: " | つぎのファイル [PageDown]",
      Ko: " | 다음 파일 [PageDown]:",
      Vi: " | File Kế [PageDown]:",
    },
    {
      Text: "TEXT_PREV_POS",
      Zh: " | 上一个位置 [Up]:",
      En: " | Previous Pos [Up]:",
      Es: " | Posición Anterior [Up]:",
      Id: " | Posisi Sebelumnya [Atas]:",
      Ja: " | 前のポジション [上矢印]",
      Ko: " | 이전 위치 [올라]:",
      Vi: " | Vị Trí Trước [TRÊN]:",
    },
    {
      Text: "TEXT_NEXT_POS",
      Zh: " | 下一个位置 [Down]:",
      En: " | Next Pos [Down]:",
      Es: " | Posición Siguiente [Down]:",
      Id: " | Posisi Berikutnya [Bawah]:",
      Ja: " | つぎのポジション [下]:",
      Ko: " | 다음 위치 [낮추다]:",
      Vi: " | Vị Trí Kế [Thấp hơn]:",
    },
    {
      Text: "TEXT_ANTI_DITHER",
      Zh: "反虚化",
      En: "Anti Dither",
      Es: "Anti Dither",
      Id: "Anti Dither",
      Ja: "アンチディザ",
      Ko: "안티 디더",
      Vi: "Chống làm mờ nhân vật",
    },
    {
      Text: "TEXT_SET_DELAY_LEFT",
      Zh: " | 延迟 [Left]:",
      En: " | Set Delay [Left]:",
      Es: " | Establecer Retraso [Izquierda]:",
      Id: " | Atur Jeda [Kiri]:",
      Ja: " | 遅延を設定する [左]:",
      Ko: " | 지연 설정 [왼쪽]:",
      Vi: " | Đặt Độ Trễ [Bên trái]:",
    },
    {
      Text: "TEXT_SELECT_RIGHT",
      Zh: " | 选择pos [Right]:",
      En: " | Select [Right]:",
      Es: " | Seleccionar [Derecha]:",
      Id: " | Pilih [Kanan]:",
      Ja: " | 選択する [右]:",
      Ko: " | 선택하다 [카난]:",
      Vi: " | Chọn [Phải]:",
    },
    {
      Text: "TEXT_IS_LAST_FILE",
      Zh: "这是最后一个文件",
      En: "is the last file",
      Es: "es el último archivo",
      Id: "adalah file terakhir",
      Ja: "最後のファイルです",
      Ko: "마지막 파일입니다",
      Vi: "là file cuối cùng",
    },
    {
      Text: "TEXT_IS_FIRST_FILE",
      Zh: "这是第一个文件",
      En: "is the first file",
      Es: "es el primer archivo",
      Id: "adalah file pertama",
      Ja: "最初のファイルです",
      Ko: "첫 번째 파일입니다",
      Vi: "là file đầu tiên",
    },
    {
      Text: "TEXT_IS_LAST_POS",
      Zh: "这是最后一个点位",
      En: "is the last position",
      Es: "es la última posición",
      Id: "adalah posisi terakhir",
      Ja: "最初の位置",
      Ko: "첫 번째 위치입니다",
      Vi: "là vị trí cuối cùng",
    },
    {
      Text: "TEXT_IS_FIRST_POS",
      Zh: "这是第一个点位",
      En: "is the first position",
      Es: "es la primera posición",
      Id: "adalah posisi pertama",
      Ja: "最初の位置",
      Ko: "첫 번째 위치입니다",
      Vi: "là vị trí đầu tiên",
    },
    {
      Text: "TEXT_CUSTOM_TP_AUTO_MODE_SET_DELAY",
      Zh: "自定义传送:自动模式:设置延迟",
      En: "Custom Teleport:Auto Mode:Set Delay",
      Es: "Teletransporte Personalizado:Modo Automático:Establecer Retraso",
      Id: "Teleportasi Kustom:Mode Otomatis:Atur Jeda",
      Ja: "カスタムテレポート:自動モード:遅延の設定",
      Ko: "사용자 지정 텔레포트: 자동 모드: 지연 설정",
      Vi: "Dịch chuyển tùy chỉnh:Chế độ tự động:Thiết lập độ trễ",
    },
    {
      Text: "TEXT_ENTER_DELAY",
      Zh: "请输入延迟 (秒)",
      En: "Please enter Delay (s)",
      Es: "Por favor, introduzca el retraso (s)",
      Id: "Silakan masukkan Jeda (detik)",
      Ja: "遅延を入力してください (秒)",
      Ko: "지연을 입력하세요 (초)",
      Vi: "Hãy nhập độ trễ (giây)",
    },
    {
      Text: "TEXT_SECONDS",
      Zh: "秒",
      En: "seconds",
      Es: "segundos",
      Id: "detik",
      Ja: "秒",
      Ko: "초",
      Vi: "giây",
    },
    {
      Text: "TEXT_GO",
      Zh: "出发",
      En: "Go",
      Es: "Ir",
      Id: "Pergi",
      Ja: "行く",
      Ko: "가다",
      Vi: "Đi",
    },
    {
      Text: "TEXT_AUTO_MODE",
      Zh: "自动模式",
      En: "Auto Mode",
      Es: "Modo Automático",
      Id: "Mode Otomatis",
      Ja: "オートモード",
      Ko: "자동 모드",
      Vi: "Tự Động",
    },
    {
      Text: "TEXT_CUSTOM_TP_CURR_POS_SELECT",
      Zh: "自定义传送:当前序号:选择",
      En: "Custom Teleport:Current Position:Select",
      Es: "Teletransporte Personalizado:Posición Actual:Seleccionar",
      Id: "Teleportasi Kustom:Posisi Saat Ini:Pilih",
      Ja: "カスタムテレポート:現在の位置:選択",
      Ko: "사용자 지정 텔레포트:현재 위치:선택",
      Vi: "Dịch chuyển tùy chỉnh:Vị trí hiện tại:Chọn",
    },
    {
      Text: "TEXT_ENTER_CURR_NUM",
      Zh: "请输入当前序号",
      En: "Please enter current num",
      Es: "Por favor, introduzca el número actual",
      Id: "Silakan masukkan Nomor saat ini",
      Ja: "現在の番号を入力してください",
      Ko: "현재 번호를 입력하세요",
      Vi: "Xin vui lòng nhập vị tri",
    },
    {
      Text: "TEXT_AUTO_MODE_END",
      Zh: " | 自动模式 [End]:",
      En: " | Auto Mode [End]:",
      Es: " | Modo Automático [End]:",
      Id: " | Mode Otomatis [End]:",
      Ja: " | オートモード [End]:",
      Ko: " | 자동 모드 [End]:",
      Vi: " | Tự Động [End]:",
    },
    {
      Text: "TEXT_INFINITE_STAMINA",
      Zh: "无限体力",
      En: "Infinite Stamina",
      Es: "Estamina Infinita",
      Id: "Stamina Tak Terbatas",
      Ja: "無限のスタミナ",
      Ko: "무한한 체력",
      Vi: "Vô hạn năng lượng",
    },
    {
      Text: "TEXT_CUSTOM_UID",
      Zh: "自定义UID",
      En: "Custom UID",
      Es: "UID Personalizado",
      Id: "UID Kustom",
      Ja: "カスタムUID",
      Ko: "사용자 정의 UID",
      Vi: "UID Tùy Chỉnh",
    },
    {
      Text: "HEADING_PLAYER",
      Zh: "玩家",
      En: "Player",
      Es: "Jugador",
      Id: "Pemain",
      Ja: "プレーヤー",
      Ko: "플레이어",
      Vi: "Người chơi",
    },
    {
      Text: "HEADING_WORLD",
      Zh: "世界",
      En: "World",
      Es: "Mundo",
      Id: "Dunia",
      Ja: "世界",
      Ko: "세계",
      Vi: "Thế giới",
    },
    {
      Text: "HEADING_VISUAL",
      Zh: "视觉",
      En: "Visual",
      Es: "Visual",
      Id: "Visual",
      Ja: "ビジュアル",
      Ko: "시각적",
      Vi: "Thị giác",
    },
    {
      Text: "TEXT_HIDE_HUD",
      Zh: "隐藏HUD",
      En: "Hide HUD",
      Es: "Ocultar Interfaz",
      Id: "Sembunyikan HUD",
      Ja: "HUDを非表示",
      Ko: "HUD 숨기기",
      Vi: "Ẩn HUD",
    },
    {
      Text: "TEXT_HIDE_DAMAGE_TEXT",
      Zh: "隐藏伤害文字",
      En: "Hide Damage Text",
      Es: "Ocultar Texto de Daño",
      Id: "Sembunyikan Teks Kerusakan",
      Ja: "ダメージテキストを非表示",
      Ko: "손상 텍스트 숨기기",
      Vi: "Không hiện sát thương",
    },
    {
      Text: "TEXT_MARK_TELEPORT",
      Zh: "标记传送 [T]",
      En: "Mark Teleport [T]",
      Es: "Marcar Teletransporte [T]",
      Id: "Tandai Teleport [T]",
      Ja: "マークテレポート [T]",
      Ko: "마크 텔레포트 [T]",
      Vi: "Đánh dấu để dịch chuyển [T]",
    },
    {
      Text: "TEXT_ONLY_HATE",
      Zh: "只有仇恨",
      En: "Only Aggro",
      Es: "Solo Agresivo",
      Id: "Hanya Kebencian",
      Ja: "まさにアグレッシブ",
      Ko: "그냥 공격적",
      Vi: "Chỉ hung hăng",
    },
    {
      Text: "TEXT_INFINITY",
      Zh: "无限",
      En: "Infinity",
      Es: "Infinito",
      Id: "Tak Terbatas",
      Ja: "無限",
      Ko: "무한대",
      Vi: "Vô hạn",
    },
    {
      Text: "HEADING_TELEPORT",
      Zh: "传送",
      En: "Teleport",
      Es: "Teletransporte",
      Id: "Teleportasi",
      Ja: "テレポート",
      Ko: "순간이동",
      Vi: "Dịch chuyển",
    },
    {
      Text: "HEADING_DEBUG",
      Zh: "调试",
      En: "Debug",
      Es: "Depurar",
      Id: "Debug",
      Ja: "デバッグ",
      Ko: "디버그",
      Vi: "Gỡ lỗi",
    },
    {
      Text: "TEXT_DEBUG_ENTITY",
      Zh: "调试实体",
      En: "Entity Debugger",
      Es: "Depurar de Entidades",
      Id: "Debugger Entitas",
      Ja: "エンティティデバッガー",
      Ko: "엔티티 디버거",
      Vi: "Trình gỡ lỗi thực thể",
    },
    {
      Text: "TEXT_AUTO_DESTROY",
      Zh: "自动销毁 [Num1]",
      En: "Auto Mining [Num1]",
      Es: "Minería Automática [Num1]",
      Id: "Penambangan Otomatis [Num1]",
      Ja: "自動マイニング [Num1]",
      Ko: "자동 채굴 [Num1]",
      Vi: "Khai thác tự động",
    },
    {
      Text: "TEXT_NEW_KILL_AURA",
      Zh: "杀戮光环",
      En: "Auto Kill Enemies",
      Es: "Mata Enemigos Automáticamente",
      Id: "Bunuh Musuh Otomatis",
      Ja: "敵を自動で倒す",
      Ko: "자동 적 사살",
      Vi: "Tự động tiêu diệt kẻ thù",
    },
    {
      Text: "TEXT_WORLD_SPEED",
      Zh: "世界速度",
      En: "World Speed",
      Es: "Velocidad del Mundo",
      Id: "Kecepatan Dunia",
      Ja: "世界スピード",
      Ko: "세계 속도",
      Vi: "Tốc Độ Thế Giới",
    },
    {
      Text: "TEXT_KILL_ANIMAL",
      Zh: "杀死动物",
      En: "Kill Animal",
      Es: "Matar Animal",
      Id: "Bunuh Hewan",
      Ja: "動物を殺す",
      Ko: "동물을 죽이다",
      Vi: "Giết Động Vật",
    },
    {
      Text: "TEXT_SAVE_CONFIG",
      Zh: "保存配置",
      En: "Save Config",
      Es: "Guardar Configuración",
      Id: "Simpan Konfigurasi",
      Ja: "設定を保存",
      Ko: "구성 저장",
      Vi: "Lưu Cấu hình",
    },
    {
      Text: "TEXT_LANGUAGE",
      Zh: "语言",
      En: "Language",
      Es: "Idioma",
      Id: "Bahasa",
      Ja: "言語",
      Ko: "언어",
      Vi: "Ngôn ngữ",
    },
    {
      Text: "TEXT_CONSOLE_COMMAND",
      Zh: "UE4虚幻控制台命令",
      En: "UE4 Console Command",
      Es: "UE4 Consola de comandos",
      Id: "Perintah Konsol UE4",
      Ja: "UE4コンソール コマンド",
      Ko: "UE4 콘솔 명령",
      Vi: "Lệnh điều khiển UE4",
    },
    {
      Text: "TEXT_FOV",
      Zh: "眼界",
      En: "Field of Vision",
      Es: "Campo de visión",
      Id: "Sudut Pandang",
      Ja: "視野角",
      Ko: "시야",
      Vi: "Tầm nhìn",
    },
    {
      Text: "TEXT_SHOW_FPS",
      Zh: "显示FPS",
      En: "Show FPS",
      Es: "Mostrar FPS",
      Id: "Tampilkan FPS",
      Ja: "FPSを表示",
      Ko: "FPS 표시",
      Vi: "Chương FPS",
    },
    {
      Text: "TEXT_FPS_UNLOCKER",
      Zh: "FPS解锁",
      En: "FPS Unlocker",
      Es: "Desbloqueador de FPS",
      Id: "Buka Kunci FPS",
      Ja: "FPSアンロック",
      Ko: "FPS 잠금 해제",
      Vi: "Mở khóa FPS",
    },
    {
      Text: "TEXT_SONANCE_CASKET",
      Zh: "古物交付",
      En: "CasketDelivery",
      Es: "CasketDelivery",
      Id: "CasketDelivery",
      Ja: "CasketDelivery",
      Ko: "CasketDelivery",
      Vi: "CasketDelivery",
    },
    {
      Text: "TEXT_PUZZLE",
      Zh: "解谜",
      En: "Puzzle",
      Es: "Rompecabezas",
      Id: "Teka-teki",
      Ja: "パズル",
      Ko: "퍼즐",
      Vi: "Câu đố",
    },
    {
      Text: "TEXT_ANIMAL",
      Zh: "动物",
      En: "Animal",
      Es: "Animal",
      Id: "Hewan",
      Ja: "動物",
      Ko: "동물",
      Vi: "Động vật",
    },
    {
      Text: "TEXT_TREASURE",
      Zh: "箱子",
      En: "Treasure",
      Es: "Tesoro",
      Id: "Harta",
      Ja: "宝物",
      Ko: "보물",
      Vi: "Kho báu",
    },
    {
      Text: "TEXT_COLLECTION",
      Zh: "收集品",
      En: "Collection",
      Es: "Colección",
      Id: "Koleksi",
      Ja: "コレクション",
      Ko: "수집",
      Vi: "Bộ sưu tập",
    },
    {
      Text: "TEXT_MONSTER",
      Zh: "怪物",
      En: "Monster",
      Es: "Monstruo",
      Id: "Monster",
      Ja: "モンスター",
      Ko: "괴물",
      Vi: "Quái vật",
    },
    {
      Text: "TEXT_SHOW_BOX",
      Zh: "展示方框",
      En: "Show Box",
      Es: "Mostrar Caja",
      Id: "Tampilkan Box",
      Ja: "表示ボックス",
      Ko: "쇼 박스",
      Vi: "Hiển thị hộp",
    },
    {
      Text: "TEXT_SHOW_DISTANCE",
      Zh: "显示距离",
      En: "Show Distance",
      Es: "Mostrar Distancia",
      Id: "Tampilkan Jarak",
      Ja: "距離を表示します",
      Ko: "거리 표시",
      Vi: "Hiển thị khoảng cách",
    },
    {
      Text: "TEXT_SHOW_NAME",
      Zh: "显示名称",
      En: "Show Name",
      Es: "Mostrar Nombre",
      Id: "Tampilkan Nama",
      Ja: "ショー名",
      Ko: "이름 표시",
      Vi: "Hiện tên",
    },
    {
      Text: "HEADING_ESP",
      Zh: "透视",
      En: "ESP",
      Es: "ESP",
      Id: "ESP",
      Ja: "ESP",
      Ko: "ESP",
      Vi: "ESP",
    },
    {
      Text: "TEXT_WEATHER",
      Zh: "天气",
      En: "Weather",
      Es: "Clima",
      Id: "Cuaca",
      Ja: "天気",
      Ko: "날씨",
      Vi: "Thời tiết",
    },
    {
      Text: "TEXT_VACUUM_COLLECT",
      Zh: "吸收集品",
      En: "Collection Vacuum",
      Id: "Vakum Koleksi",
      Ja: "収集真空",
      Es: "Recolección de vacío",
      Ko: "수집 진공",
      Vi: "Thu thập chân không",
    },
    {
      Text: "TEXT_MOB_VACUUM",
      Zh: "吸怪",
      En: "Monster Vacuum",
      Id: "Vakum Musuh",
      Ja: "モンスターバキューム",
      Es: "Aspiradora monstruo",
      Ko: "몬스터 진공 청소기",
      Vi: "Máy hút bụi quái vật",
    },
    {
      Text: "HEADING_FILTER",
      Zh: "筛选",
      En: "Filter",
      Es: "Filtro",
      Id: "Saring",
      Ja: "フィルター",
      Ko: "필터",
      Vi: "Lọc",
    },
    {
      Text: "TEXT_SUNNY",
      Zh: "晴天",
      En: "Sunny",
      Es: "Soleado",
      Id: "Cerah",
      Ja: "SUNNY",
      Ko: "밝은",
      Vi: "Sáng",
    },
    {
      Text: "TEXT_CLOUDY",
      Zh: "多云的",
      En: "Cloudy",
      Es: "Nublado",
      Id: "Berawan",
      Ja: "曇り",
      Ko: "흐림",
      Vi: "Nhiều mây",
    },
    {
      Text: "TEXT_THUNDER_RAIN",
      Zh: "雷雨",
      En: "Thunderstorm",
      Es: "Tormenta",
      Id: "Hujan Badai",
      Ja: "雷雨",
      Ko: "뇌우",
      Vi: "Dông",
    },
    {
      Text: "TEXT_SNOW",
      Zh: "雪",
      En: "Snow",
      Es: "Nieve",
      Id: "Salju",
      Ja: "雪",
      Ko: "눈",
      Vi: "Tuyết",
    },
    {
      Text: "TEXT_RAIN",
      Zh: "雨",
      En: "Rain",
      Es: "Lluvia",
      Id: "Hujan",
      Ja: "雨",
      Ko: "비",
      Vi: "Cơn mưa",
    },
    {
      Text: "TEXT_ROCK",
      Zh: "岩石解谜",
      En: "Rock",
      Es: "Roca",
      Id: "Batu",
      Ja: "ロック",
      Ko: "바위",
      Vi: "Đá",
    },
    {
      Text: "TEXT_MUTTERFLY",
      Zh: "隙声蝶",
      En: "Mutterfly",
      Es: "Mutterfly",
      Id: "Kupu-kupu",
      Ja: "隙声蝶",
      Ko: "Mutterfly",
      Vi: "Mutterfly",
    },
    {
      Text: "TEXT_BLOBFLY",
      Zh: "飞猎手",
      En: "Blobfly",
      Es: "Blobfly",
      Id: "Blobfly",
      Ja: "Blobfly",
      Ko: "Blobfly",
      Vi: "Blobfly",
    },
    {
      Text: "TEXT_ILLUSIVE_SPRINT",
      Zh: "虚幻的冲刺",
      En: "Illusive Sprint",
      Es: "Sprint Ilusivo",
      Id: "Sprint ilusif",
      Ja: "幻想的なスプリント",
      Ko: "환상적인 스프린트",
      Vi: "Chạy nước rút ảo ảnh",
    },
    {
      Text: "TEXT_NOCLIP",
      Zh: "空中飞人",
      En: "No Clip",
      Es: "No Clip",
      Id: "No Clip",
      Ja: "No Clip",
      Ko: "No Clip",
      Vi: "No Clip",
    },
    {
      Text: "TEXT_PLOT_SKIP",
      Zh: "剧情跳过",
      En: "Plot Skip",
      Es: "Saltate la Historia",
      Id: "Lewati Cerita",
      Ja: "プロットのスキップ",
      Ko: "스토리 건너뛰기",
      Vi: "Bỏ qua câu chuyện",
    },
    {
      Text: "TEXT_AUTO_PUZZLE",
      Zh: "自动解谜",
      En: "Auto Solve Puzzle",
      Es: "Rompecabezas de resolución automática",
      Id: "Pemecahan Teka-teki Otomatis",
      Ja: "自動パズル解決",
      Ko: "자동 퍼즐 풀기",
      Vi: "Tự động giải câu đố",
    },
    {
      Text: "TEXT_QUEST_TP",
      Zh: "任务传送 [V]",
      En: "Quest Teleport [V]",
      Es: "Misión de teletransporte [V]",
      Id: "Teleportasi Quest [V]",
      Ja: "クエストテレポート [V]",
      Ko: "퀘스트 텔레포트 [V]",
      Vi: "Nhiệm vụ dịch chuyển [V]",
    },
    {
      Text: "TEXT_ALWAYS_CRIT",
      Zh: "总是致命一击",
      En: "Always Critical Hit",
      Es: "Golpe siempre crítico",
      Id: "Selalu Serangan Kritis",
      Ja: "常にクリティカルヒット",
      Ko: "항상 치명타",
      Vi: "Luôn có đòn chí mạng",
    },
    {
      Text: "KUN_MOD_LOADED",
      Zh: "Kun Mod已加载",
      En: "Kun Mod Loaded",
      Es: "Kun Mod Cargado",
      Id: "Kun Mod Dimuat",
      Ja: "Kun Modロード",
      Ko: "Kun Mod 로드됨",
      Vi: "Kun Mod Đã Tải",
    },
    {
      Text: "DC_NO_ROLE",
      Zh: "您没有使用此模组所需的角色",
      En: "You don't have required role for using this mod",
      Es: "No tienes el rol requerido para usar este mod",
      Id: "Anda tidak memiliki peran yang diperlukan untuk menggunakan mod ini",
      Ja: "このMODを使用するために必要な役割がありません",
      Ko: "이 모드를 사용하려면 필요한 역할이 없습니다",
      Vi: "Bạn không có vai trò bắt buộc để sử dụng bản mod này",
    },
    {
      Text: "DC_NOT_MEMBER",
      Zh: "您不是KUNMODFANS Discord服务器的成员",
      En: "You're not a member of KUNMODFANS Discord Server",
      Es: "No eres miembro del servidor de Discord de KUNMODFANS",
      Id: "Anda bukan anggota Server Discord KUNMODFANS",
      Ja: "あなたはKUNMODFANS Discordサーバーのメンバーではありません",
      Ko: "당신은 KUNMODFANS Discord 서버의 회원이 아닙니다",
      Vi: "Bạn không phải là thành viên của KUNMODFANS Discord Server",
    },
    {
      Text: "DC_EXPIRED_TOKEN",
      Zh: "令牌已过期",
      En: "Token Expired",
      Es: "Token Caducado",
      Id: "Token Kedaluwarsa",
      Ja: "トークンの有効期限が切れました",
      Ko: "토큰 만료됨",
      Vi: "Mã thông báo đã hết hạn",
    },
    {
      Text: "DC_INVALID_TOKEN",
      Zh: "令牌无效",
      En: "Token Invalid",
      Es: "Token Inválido",
      Id: "Token Tidak Valid",
      Ja: "トークンが無効です",
      Ko: "토큰이 유효하지 않습니다",
      Vi: "Thẻ không hợp lệ",
    },
  ];

  static ModTr = (string) => {
    const Find = ModLanguage.translate.find(
      (translate) => translate.Text == string
    );
    if (Find) {
      return Find[this.GetCurrLang()] || Find.Text;
    } else {
      return string; // return original string if no translation found
    }
  };
}

exports.ModLanguage = ModLanguage;
